Jenkins POST steps

diff --git a/cicd/Jenkinsfile b/cicd/Jenkinsfile
--- a/cicd/Jenkinsfile
+++ b/cicd/Jenkinsfile
@@ -1,6 +1,11 @@
 pipeline {
     agent any
     stages {
+        stage('test') {
+            steps {
+                sh 'echo "FAIL Test!"; exit 1'
+            }
+        }
         stage('build') {
             steps {
                 sh 'python --version'
@@ -21,6 +26,24 @@ pipeline {
                     sh 'ls -ltr'
                 }
             }
+        }
+    }
+    post {
+        always {
+            echo 'This will always run'
+        }
+        success {
+            echo 'This will run only if successful'
+        }
+        failure {
+            echo 'This will run only if failed'
+        }
+        unstable {
+            echo 'This will run only if the run was marked as unstable'
+        }
+        changed {
+            echo 'This will run only if the state of the Pipeline has changed'
+            echo 'For example, if the Pipeline was previously failing but is now successful'
         }
     }
 }
